---
id: Controller
name: Controller
full: Controller library
description: The controller part of an MVC system for Horde.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Controller
authors:
  -
    name: Mike Naberezny
    user: mnaberez
    email: mike@naberezny.com
    active: false
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Injector: ^2
      pear.horde.org/Horde_Log: ^2
      pear.horde.org/Horde_Support: ^2
      pear.horde.org/Horde_Util: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
    ext:
      mbstring: '*'
      zlib: '*'
